### PR TITLE
feat: add DocSearch as recommended by vuepress

### PR DESCRIPTION
**Pull request by s-pace**
👋 team,

I am working on DocSearch. [We have an integration for Vuepress](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search). We thought it is a shame you can not also used this search that you can [find on vuejs for example](https://vuejs.org/).

This PR will add DocSearch to the documentation website. It will allow a user to have a learn-as-you-type experience by displaying results thanks to a dropdown in a live way.

Let me know if you need anything.

### CODE REVIEW

**Comment by s-pace** [comment]
Sure, it enables the search as you can see on the vuepress website:
image

**Comment by BaileyJM02** [comment]
Okay, thank you for explaining, I can't see this working on your branch, could you please have another look?

**Comment by s-pace** [comment]
It does work on. Please search:
https://jexia-docsearch.surge.sh/

**Comment by MishaJexia** [comment]
Nice product. I like it. Let's come back to this point at the end of this year. We will have a better understanding of traffic so we will have an understanding of the payment part. 
Thank you for suggesting.

**Comment by s-pace** [comment]
It is entirely free =)

**Comment by MishaJexia** [comment]
em... But see here it is paid after certain amount https://www.algolia.com/pricing/ 
or I read it wrongly, @s-pace?

**Comment by s-pace** [comment]
[DocSearch is provided entirely for free](https://docsearch.algolia.com/) 🚀  We just want tot give back to the community

**Comment by MishaJexia** [comment]
@s-pace, we have some responsibility in front of our clients and obligations for GDPR and after some evaluation, we decided to take extra time to learn impact of this change. I will come back to you as soon as will have any updates.

**Comment by veger** [comment]
Thanks for your offer and PR!
Unfortunately we decided not to implement this.

**Pull request closed without merging**
