### PR TITLE
add links to the list of basic services

### PR DESCRIPTION
**Pull request by octavian-nita**
Added link(s) to the basic services section(s), as per @BaileyJM02 good suggestion.

### CODE REVIEW

**Comment by octavian-nita** [comment]
You mean, under the Services section as well as Application hosting and Access control, link each of the respective items to its own details page?

**Comment by BaileyJM02** [comment]
So it would become this: 
```md
[basic services](#services) ([data and file storage](/the-correct-url), [user management](/ums), [access control](/access-control), etc.)
```
The links aren't correct but leaving the "basic services" as it is and then the others to their associated page. :+1:

**Comment by MishaJexia** [comment]
Hi there. Do you think it will be more reasonable to add list of all services available on Jexia and add links to them?

**Comment by octavian-nita** [comment]
> Hi there. Do you think it will be more reasonable to add list of all services available on Jexia and add links to them?

I will try to make both changes, let's see how this looks like.

**Comment by MishaJexia** [comment]
@BaileyJM02 , absolute might be even better for SEO optimization :)

**Comment by octavian-nita** [comment]
> The layout looks good to me, though could be use relative URL paths instead of absolute URLs please 😄

Indeed, that was my first option too but then I looked around in the docs and saw that many URLs were absolute. Then again those may have been links to the main site, not the docs themselves.

I'll change them but, we should then be aware we depend on the structure/layout of the docs module.

**Comment by BaileyJM02** [comment]
There now seems to be some conflicting views and this may have caused confusion, by relative urls, I mean **root-relative URLs**, this is where the URLs look like so:
```
Link to home page
href="/shop/"

Link to product page
href="/shop/t-shirts/t-shirt-life-is-good/"
```
And it is what we *now* have since the last commit. These don't have any effect on SEO (that's noticeable) as they don't interfere with canonical tags, to the extent that a `href=../../page.html"` would.

The main pros for me requesting relative URLs are as follows:
- Allows testing to have a 1:1 resemblance of the production environment
- If the domain is changed again, like it was recently, we would have to change all URLs, where as we could just leave these as they are dnd it would work as expected.
- If a protocol change was to occur like the `http` to `https` changes again, we would only have to change server side (apache etc) things and nothing within the docs other than maybe image urls from external sources.
- By using root-relative URLs, we can deploy on any domain and still ensure that SEO is not effected.

---
Articles for ruther reading:
- [Google 10 Years Later: Absolute Vs Relative URLs Doesn't Matter For SEO](https://www.seroundtable.com/google-absolute-vs-relative-urls-26001.html)
- [StackOverflow: Absolute vs relative URLs](https://stackoverflow.com/questions/2005079/absolute-vs-relative-urls)

**Comment by MishaJexia** [comment]
Hm... Make sense @BaileyJM02 . I will merge this PR, but we will migrate all URL to the relative with the next PR. I need to see how it is working with base URL etc..

**Pull request merged**
